### ISSUE TITLE
request: arm64 (aka aarch64) builds

### ISSUE THREAD

**Issue by valerie-makes** [pyston/pyston_v1#1441]
>  If you would like support for a different OS, let us know by filing an issue in our issue tracker.

Would it be possible to provide arm64 builds for Ubuntu / portable Linux? I have an M1 MacBook upon which I can run Linux VMs inside Docker or Parallels - it would be nice to try running Pyston natively in these VMs :) This would also enable running Pyston on 64-bit Raspberry Pi devices.

Tangentially related: #1438 for macOS builds

**Comment by kmod** [comment]
This is more work for us than for other projects because we generate machine code at runtime, so the actual behavior would have to change in addition to changing the compiler settings.  Our JIT is essentially a macroassembler so it's directly referencing x86-64 instructions, though I don't think we use anything that crazy so it might be a pretty close 1-1 mapping to arm64.

So it's on our roadmap, but there would have to be pretty significant interest for us to invest in making our JIT retargetable.
